# Introducción y manipulación de datos con Pandas

**Pandas**

Biblioteca de código abierto que proporciona estructuras de datos y herramientas de análisis de datos de alto rendimiento y fáciles de usar.

- Manejo de archivos
- Series (1D)
- Dataframes (2D)
- Panels (3D)

__________________

## Librerías

Empecemos con importando las librerías necesarias

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import fundamentos_ML.utils.paths as path

## Series

En la series con pandas, tenemos del lado izquierdo los índices, mientras que del lado derecho, la información.

In [3]:
series = pd.Series([5, 10, 15, 20, 25])
series

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [4]:
# Type of the argument
type(series)

pandas.core.series.Series

Podemos acceder a los elementos mediante el uso de corchetes

In [5]:
series[3]

20

En las series, también podemos usar caracteres

In [6]:
cad = pd.Series(['p', 'a', 'o', 'l', 'a'])
cad

0    p
1    a
2    o
3    l
4    a
dtype: object

## DataFrame

Veamos el ejemplo más sencillo de un dataframe, donde se le pasa una lista de strings.

In [7]:
a = ['Hello', 'World', '!']
df = pd.DataFrame(a)
df

       0
0  Hello
1  World
2      !

Otra forma de colocar el nombre de las columnas es por medio de los diccionarios como se muestra a continuación:

In [8]:
data = {'Name': ['Juan', 'Ana', 'Jose', 'Arturo'],
'Age': [25, 18, 23, 17],
'Country': ['MX', 'CO', 'BR', 'MX']}
df = pd.DataFrame(data)
df

     Name  Age Country
0    Juan   25      MX
1     Ana   18      CO
2    Jose   23      BR
3  Arturo   17      MX

In [9]:
# Filtering by the columns of interest
df[['Name', 'Country']]

     Name Country
0    Juan      MX
1     Ana      CO
2    Jose      BR
3  Arturo      MX

Ahora, veamos la forma de leer archivos y convertirlo en un dataframe

In [27]:
# Read data
input_data = path.data_raw_dir("canciones-2018.csv")
data = pd.read_csv(input_data)
data.head(6)

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,6DCZcSspjsKoFjzjrWoCd,God's Plan,Drake,0.754,0.449,7.0,-9.211,1.0,0.1090,0.0332,0.000083,0.552,0.357,77.169,198973.0,4.0
1,3ee8Jmje8o58CHK66QrVC,SAD!,XXXTENTACION,0.740,0.613,8.0,-4.880,1.0,0.1450,0.2580,0.003720,0.123,0.473,75.023,166606.0,4.0
2,0e7ipj03S05BNilyu5bRz,rockstar (feat. 21 Savage),Post Malone,0.587,0.535,5.0,-6.090,0.0,0.0898,0.1170,0.000066,0.131,0.140,159.847,218147.0,4.0
3,3swc6WTsr7rl9DqQKQA55,Psycho (feat. Ty Dolla $ign),Post Malone,0.739,0.559,8.0,-8.011,1.0,0.1170,0.5800,0.000000,0.112,0.439,140.124,221440.0,4.0
4,2G7V7zsVDxg1yRsu7Ew9R,In My Feelings,Drake,0.835,0.626,1.0,-5.833,1.0,0.1250,0.0589,0.000060,0.396,0.350,91.030,217925.0,4.0
5,7dt6x5M1jzdTEt8oCbisT,Better Now,Post Malone,0.680,0.563,10.0,-5.843,1.0,0.0454,0.3540,0.000000,0.136,0.374,145.028,231267.0,4.0

A continuación, se expondrán diferentes funciones útiles para la manipulación de datos

In [12]:
# Filtering the column 'artists' with index 5
artist = data.artists
artist[5]

'Post Malone'

In [28]:
# Filtering the data by the index 15
info = data.iloc[5]
info

id                  7dt6x5M1jzdTEt8oCbisT
name                           Better Now
artists                       Post Malone
danceability                         0.68
energy                              0.563
key                                  10.0
loudness                           -5.843
mode                                  1.0
speechiness                        0.0454
acousticness                        0.354
instrumentalness                      0.0
liveness                            0.136
valence                             0.374
tempo                             145.028
duration_ms                      231267.0
time_signature                        4.0
Name: 5, dtype: object

In [16]:
# Last five rows
data.tail(5)

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
95,630sXRhIcfwr2e4RdNtjK,Rewrite The Stars,Zac Efron,0.684,0.619,10.0,-7.005,1.0,0.0386,0.0716,0.000000,0.1220,0.2840,125.046,217440.0,4.0
96,2xmrfQpmS2iJExTlklLoA,I Miss You (feat. Julia Michaels),Clean Bandit,0.638,0.658,3.0,-6.318,1.0,0.0456,0.2450,0.000004,0.0919,0.3300,105.076,205748.0,4.0
97,5WvAo7DNuPRmk4APhdPzi,No Brainer,DJ Khaled,0.552,0.760,0.0,-4.706,1.0,0.3420,0.0733,0.000000,0.0865,0.6390,135.702,260000.0,5.0
98,1j4kHkkpqZRBwE0A4CN4Y,Dusk Till Dawn - Radio Edit,ZAYN,0.258,0.437,11.0,-6.593,0.0,0.0390,0.1010,0.000001,0.1060,0.0967,180.043,239000.0,4.0
99,3EPXxR3ImUwfayaurPi3c,Be Alright,Dean Lewis,0.553,0.586,11.0,-6.319,1.0,0.0362,0.6970,0.000000,0.0813,0.4430,126.684,196373.0,4.0

In [17]:
# Number of rows and columns
data.shape

(100, 16)

In [18]:
# Name of the columns
data.columns

Index(['id', 'name', 'artists', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature'],
      dtype='object')

In [20]:
# A quick statistical description of the numerical columns
data.describe()

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
count,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00
mean,0.71646,0.659060,5.330000,-5.677640,0.590000,0.115569,0.195701,0.001584,0.158302,0.484443,119.904180,205206.780000,3.98
std,0.13107,0.145067,3.676447,1.777577,0.494311,0.104527,0.220946,0.013449,0.111662,0.206145,28.795984,40007.893404,0.20
min,0.25800,0.296000,0.000000,-10.109000,0.000000,0.023200,0.000282,0.000000,0.021500,0.079600,64.934000,95467.000000,3.00
25%,0.63550,0.562000,1.750000,-6.650500,0.000000,0.045350,0.040225,0.000000,0.094675,0.341000,95.730750,184680.000000,4.00
50%,0.73300,0.678000,5.000000,-5.566500,1.000000,0.074950,0.109000,0.000000,0.118500,0.470500,120.116000,205047.500000,4.00
75%,0.79825,0.772250,8.250000,-4.363750,1.000000,0.137000,0.247750,0.000031,0.170750,0.641500,140.022750,221493.250000,4.00
max,0.96400,0.909000,11.000000,-2.384000,1.000000,0.530000,0.934000,0.134000,0.636000,0.931000,198.075000,417920.000000,5.00

In [21]:
# General information about the columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                100 non-null    object
 1   name              100 non-null    object
 2   artists           100 non-null    object
 3   danceability      100 non-null    float64
 4   energy            100 non-null    float64
 5   key               100 non-null    float64
 6   loudness          100 non-null    float64
 7   mode              100 non-null    float64
 8   speechiness       100 non-null    float64
 9   acousticness      100 non-null    float64
 10  instrumentalness  100 non-null    float64
 11  liveness          100 non-null    float64
 12  valence           100 non-null    float64
 13  tempo             100 non-null    float64
 14  duration_ms       100 non-null    float64
 15  time_signature    100 non-null    float64
dtypes: float64(13), object(3)
memory usage: 12.6+ KB

In [25]:
# Sorting elements by the index
data.sort_index(axis=0, ascending=False)

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
99,3EPXxR3ImUwfayaurPi3c,Be Alright,Dean Lewis,0.553,0.586,11.0,-6.319,1.0,0.0362,0.6970,0.000000,0.0813,0.4430,126.684,196373.0,4.0
98,1j4kHkkpqZRBwE0A4CN4Y,Dusk Till Dawn - Radio Edit,ZAYN,0.258,0.437,11.0,-6.593,0.0,0.0390,0.1010,0.000001,0.1060,0.0967,180.043,239000.0,4.0
97,5WvAo7DNuPRmk4APhdPzi,No Brainer,DJ Khaled,0.552,0.760,0.0,-4.706,1.0,0.3420,0.0733,0.000000,0.0865,0.6390,135.702,260000.0,5.0
96,2xmrfQpmS2iJExTlklLoA,I Miss You (feat. Julia Michaels),Clean Bandit,0.638,0.658,3.0,-6.318,1.0,0.0456,0.2450,0.000004,0.0919,0.3300,105.076,205748.0,4.0
95,630sXRhIcfwr2e4RdNtjK,Rewrite The Stars,Zac Efron,0.684,0.619,10.0,-7.005,1.0,0.0386,0.0716,0.000000,0.1220,0.2840,125.046,217440.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2G7V7zsVDxg1yRsu7Ew9R,In My Feelings,Drake,0.835,0.626,1.0,-5.833,1.0,0.1250,0.0589,0.000060,0.3960,0.3500,91.030,217925.0,4.0
3,3swc6WTsr7rl9DqQKQA55,Psycho (feat. Ty Dolla $ign),Post Malone,0.739,0.559,8.0,-8.011,1.0,0.1170,0.5800,0.000000,0.1120,0.4390,140.124,221440.0,4.0
2,0e7ipj03S05BNilyu5bRz,rockstar (feat. 21 Savage),Post Malone,0.587,0.535,5.0,-6.090,0.0,0.0898,0.1170,0.000066,0.1310,0.1400,159.847,218147.0,4.0
1,3ee8Jmje8o58CHK66QrVC,SAD!,XXXTENTACION,0.740,0.613,8.0,-4.880,1.0,0.1450,0.2580,0.003720,0.1230,0.4730,75.023,166606.0,4.0
0,6DCZcSspjsKoFjzjrWoCd,God's Plan,Drake,0.754,0.449,7.0,-9.211,1.0,0.1090,0.0332,0.000083,0.5520,0.3570,77.169,198973.0,4.0

In [26]:
# Sorting elementes by a column
subset = data[['name','tempo','duration_ms']]
subset.sort_values(by='tempo',axis=0 , ascending=True)

                             name    tempo  duration_ms
38                        changes   64.934     121887.0
1                            SAD!   75.023     166606.0
0                      God's Plan   77.169     198973.0
71                  Feel It Still   79.028     163253.0
78                       Criminal   79.997     232550.0
..                            ...      ...          ...
98    Dusk Till Dawn - Radio Edit  180.043     239000.0
17                              X  180.073     173628.0
81                       Stir Fry  181.967     190288.0
93                     This Is Me  191.702     234707.0
85  Coraz?n (feat. Nego do Borel)  198.075     184720.0

[100 rows x 3 columns]